# Site settings
title: "Jekyll Simple Base"
email: "team@variantstudios.com"
description: "Our base repo for jekyll-based sites that use CloudCannon"
baseurl: "" # the subpath of your site, e.g. /blog/ - keep empty!
url: "" # the base hostname & protocol for your site - don't include the forward slash
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Cloudinary URL - something like: https://res.cloudinary.com/domain-com/
cloudinaryurl:

# typekit - Because we all need nice type faces.
typekit:

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id:

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
